query languages($page: Int, $search: String, $limit: Int, $sort: String) {
  languages(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      nativeName
      code
      phpLocaleCode
      rtl
      sort
      active
      createdAt
      updatedAt
    }
  }
}
