mutation saveLanguage(
  $id: String
  $code: String
  $name: String
  $nativeName: String
  $active: Boolean
  $phpLocaleCode: String
  $rtl: Boolean
  $sort: Int
) {
  saveLanguage(
    id: $id
    code: $code
    phpLocaleCode: $phpLocaleCode
    rtl: $rtl
    name: $name
    nativeName: $nativeName
    sort: $sort
    active: $active
  ) {
    id
    name
    nativeName
    code
    phpLocaleCode
    rtl
    sort
    active
    createdAt
    updatedAt
  }
}
