query faqs($page: Int, $search: String, $limit: Int, $sort: String) {
  faqs(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      question
      topic
      answer
      active
      createdAt
      updatedAt
    }
  }
}
