mutation saveFaq(
  $id: String!
  $question: String
  $topic: String
  $answer: String
  $active: Boolean
) {
  saveFaq(
    id: $id
    question: $question
    topic: $topic
    answer: $answer
    active: $active
  ) {
    id
    question
    topic
    answer
    active
  }
}
