mutation saveFaq(
  $id: String!
  $question: String
  $topic: String
  $answer: String
  $active: Boolean
  $store: ID
) {
  saveFaq(
    id: $id
    question: $question
    topic: $topic
    answer: $answer
    active: $active
    store: $store
  ) {
    id
    question
    topic
    answer
    active
    store
  }
}

# {
#   "id": "new",
#   "question": "Ad",
#   "answer": "dfa",
#   "store": "60fb92e49f73050d30287cae"
# }
