query optionValues(
  $page: Int
  $limit: Int
  $search: String
  $sort: String
  $option: ID
) {
  optionValues(
    page: $page
    limit: $limit
    search: $search
    sort: $sort
    option: $option
  ) {
    count
    page
    pageSize
    data {
      id
      name
      default
      position
      direction
      isPercent
      value
    }
  }
}
