mutation saveOptionValue(
  $id: String!
  $option: ID
  $name: String
  $default: Boolean
  $position: Int
  $value: Float
  $direction: String
  $isPercent: Boolean
) {
  saveOptionValue(
    id: $id
    option: $option
    name: $name
    default: $default
    position: $position
    value: $value
    direction: $direction
    isPercent: $isPercent
  ) {
    id
    name
    default
    position
    direction
    isPercent
    value
  }
}

# {
#    "id": "new",
#   "option": "61bb47aa038cf5356c863ec3",
#    "name": "yes",
#   "default": true
#  }
