mutation saveOptionValue(
  $id: String!
  $option_id: ID
  $name: String
  $default: Boolean
  $position: Int
  $amt: Int
  $type: String
  $slug: String
  $active: Boolean
) {
  saveOptionValue(
    id: $id
    option_id: $option_id
    name: $name
    default: $default
    position: $position
    amt: $amt
    type: $type
    slug: $slug
    active: $active
  ) {
    id
    option_id
    name
    default
    position
    type
    amt
    slug
    active
  }
}

# {
#    "id": "new",
#   "option_id": "60557db71d76790db44dd096",
#    "name": "green",
#   "default": true
#  }
