mutation paypalExecute(
  $paymentId: ID!
  $payerId: String!
  $paypalPaymentId: String!
) {
  paypalExecute(
    paymentId: $paymentId
    payerId: $payerId
    paypalPaymentId: $paypalPaymentId
  ) {
    id
  }
}
