query getGdprDataDeleteRequest($id: ID!) {
  getGdprDataDeleteRequest(id: $id) {
    id
    comment
    description
    reason
    status
    user {
      id
      firstName
      lastName
      email
    }
  }
}
