query allOrders(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $status: String
  $where: String
) {
  allOrders(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    status: $status
    where: $where
  ) {
    count
    page
    pageSize
    data {
      id
      orderNo
      createdAt
      paymentMode
      paymentStatus
      userFirstName
      userLastName
      userPhone
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      address {
        firstName
        lastName
        address
        lat
        lng
      }
      items {
        pid
        posInvoiceNo
        itemOrderNo
        name
        img
        slug
        price
        qty
        subtotal
        total
        status
        vendor {
          firstName
          lastName
          phone
          address {
            address
          }
          store
        }
      }
    }
  }
}
