query allOrders(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $role: String
) {
  allOrders(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    role: $role
  ) {
    count
    page
    pageSize
    data {
      id
      orderNo
      createdAt
      user {
        firstName
        lastName
        phone
      }
      amount {
        qty
        subtotal
        tax {
          cgst
          sgst
          igst
        }
        discount
        total
        shipping
      }
      address {
        firstName
        lastName
        address
        coords {
          lat
          lng
        }
      }

      items {
        pid
        name
        img
        slug
        price
        qty
        status
        orderStatus
        vendor {
          store
        }
      }
    }
  }
}
