query allOrders($page: Int, $search: String, $limit: Int, $sort: String) {
  allOrders(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      orderNo
      createdAt
      user {
        firstName
        lastName
        phone
      }
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      address {
        firstName
        lastName
        address
        lat
        lng
      }
      items {
        pid
        posInvoiceNo
        itemOrderNo
        name
        img
        slug
        price
        qty
        status
        vendor {
          store
        }
      }
    }
  }
}
