query deliverySummary {
  orderSummary {
    _id
    count
    amount
    createdAt
    cod_paid
  }
  statusSummary {
    _id
    count
    amount
    createdAt
  }
  paymentsSummary {
    _id
    count
    amount
    cod_paid
  }
}
