query myOrders(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $status: String # Pending, Tracking, Delivered
) {
  myOrders(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    status: $status
  ) {
    count
    pageSize
    page
    data {
      id
      orderNo
      reviewed
      otp
      createdAt
      updatedAt
      codPaid
      paymentMode
      paymentTxStatus
      paymentAmount
      payment {
        amount_paid
        amount_due
      }
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      user {
        firstName
        lastName
        phone
        email
        gender
        info {
          public
          store
          storePhotos
        }
        avatar
      }
      address {
        address
        firstName
        lastName
      }
      items {
        pid
        name
        slug
        img
        price
        qty
        status
        shippingCharge
        tax
        brandName
        brandImg
        vendor {
          store
          firstName
          lastName
          phone
        }
      }
    }
  }
}
