query order($id: ID!) {
  order(id: $id) {
    id
    orderNo
    otp
    createdAt
    codPaid
    paySuccess
    payment {
      amount_paid
      amount_due
    }
    paymentMode
    paymentTxStatus
    paymentAmount
    paymentCurrency
    paymentReferenceId
    amount {
      qty
      subtotal
      tax
      discount
      total
      shipping
    }
    userFirstName
    userLastName
    userPhone
    addressId {
      id
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    items {
      pid
      posInvoiceNo
      itemOrderNo
      name
      barcode
      img
      slug
      price
      qty
      shippingCharge
      tax
      time
      options
      brandName
      brandImg
      orderStatus {
        id
        event
        tracking_id
        courier_name
      }
      vendor {
        firstName
        lastName
        phone
        address {
          address
        }
        store
      }
      status
    }
  }
}
