query orderItem($id: ID!) {
  orderItem(id: $id) {
  	  id
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      tracking
      shippingCharge
      tax
      brandName
      brandImg
    	status
  		orderStatus {
        id
        event
        tracking_id
        courier_name
      }
  }
}