query order($id: ID!) {
  order(id: $id) {
    id
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    paymentId
    invoiceId
    paymentGateway
    codPaid
    amountPaid
    amountDue
    paymentMsg
    paymentTime
    paid
    amountRefunded
    amount {
      qty
      subtotal
      tax
      discount
      total
      shipping
    }
    userFirstName
    userLastName
    userPhone
    userEmail
    addressId {
      id
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    store {
      id
      name
      email
    }
    items {
      id
      pid
      posInvoiceNo
      itemOrderNo
      name
      barcode
      img
      slug
      price
      qty
      shippingCharge
      tax
      time
      options
      brandName
      brandImg
      color
      size
      status
      type
      days
      returnReason
      vendor {
        firstName
        lastName
        phone
        address {
          address
        }
        store
      }
      status
      orderHistory {
        status
        title
        body
        icon
        public
        index
        time
      }
    }
    orderItems {
      id
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      tracking
      shippingCharge
      tax
      brandName
      brandImg
      invoiceLink
      returnValidTill
      color
      size
      trackingId
      returnTrackingId
      courierName
      returnCourierName
      type
      days
      price
      mrp
      qty
      subtotal
      total
      returnReason
      amountRefunded
      vendorInfo {
        firstName
      }
      orderHistory {
        status
        title
        body
        icon
        public
        index
        time
      }
    }
  }
}
