query orderItem($id: ID!) {
  orderItem(id: $id) {
    id
    orderId
    status
    pid
    posInvoiceNo
    itemOrderNo
    name
    slug
    img
    tracking
    shippingCharge
    price
    qty
    tax
    brandName
    brandImg
    size
    color
    trackingId
    returnTrackingId
    courierName
    returnCourierName
    days
    type
    #order level info
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    paymentId
    invoiceId
    paymentGateway
    codPaid
    amountPaid
    amountDue
    paymentMsg
    paymentTime
    paid
    userFirstName
    userLastName
    userPhone
    userEmail
    invoiceLink
    returnValidTill
    user {
      id
      firstName
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    orderHistory {
      id
      status
      title
      body
      icon
      public
      index
      time
    }
    vendor {
      firstName
      lastName
      phone
      address {
        address
      }
      store
    }
  }
}
