query orderItem($id: ID!) {
  orderItem(id: $id) {
    id
    orderId
    status
    pid
    posInvoiceNo
    itemOrderNo
    name
    slug
    img
    tracking
    shippingCharge
    price
    qty
    tax
    brandName
    brandImg
    size
    color
    trackingId
    returnTrackingId
    courierName
    returnCourierName
    days
    type
    amountRefunded
    refund {
      message
      time
      amount
      refundId
    }
    #order level info
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    paymentId
    invoiceId
    paymentGateway
    codPaid
    amountPaid
    amountDue
    totalAmountRefunded
    paymentMsg
    paymentTime
    paid
    userFirstName
    userLastName
    userPhone
    userEmail
    invoiceLink
    returnValidTill
    returnReason
    user {
      id
      firstName
    }
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    store {
      id
      name
      email
    }
    vendor {
      firstName
      lastName
      phone
      address {
        address
      }
      store
    }
    orderHistory {
      id
      status
      title
      body
      icon
      public
      index
      time
    }
  }
}
