mutation saveEmailTemplate(
  $id: String!
  $name: String
  $title: String
  $description: String
  $content: String
  $active: Boolean
) {
  saveEmailTemplate(
    id: $id
    name: $name
    title: $title
    description: $description
    content: $content
    active: $active
  ) {
    id
    name
    title
    description
    content
    link
    active
    createdAt
    updatedAt
  }
}

# {
#   "id": "60f93c6497e0ac06b0b1b1eb",
#   "name": "temp",
#   "title": "asdsf",
#   "description": "dafdsafsda",
#   "content": "<html> wala <html>"
# }
