query templates(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  templates(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      fileName
      title
      description
      templateId
      icon
      iconCdn
      content
      folder
      active
      type
      variables
      createdAt
      updatedAt
      user {
        id
        firstName
        email
        phone
      }
      store {
        id
        name
        email
      }
    }
  }
}

# query templates($folder: String, $name: String) {
#   templates(folder: $folder, name: $name)
# }
