mutation OrderRefund(
  $orderItemId: ID!
  $amount: Float!
  $note: String!
  $email: String!
  $password: String!
) {
  OrderRefund(
    orderItemId: $orderItemId
    amount: $amount
    note: $note
    email: $email
    password: $password
  ) {
    id
  }
}

# {
#   "orderItemId": "610a2c57f4773909505717d9",
#   "amount": 33.33,
#   "note": "aaa",
#   "email": "admin@litekart.in",
#   "password": "Admin"
# }
