query payments($page: Int, $search: String, $limit: Int, $sort: String) {
  payments(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      orderId
      paymentOrderId
      paymentMode
      paymentGateway
      referenceId
      status
      txMsg
      txTime
      invoiceId
      receipt
      currency
      paid
      amountPaid
      amountRefunded
      amountDue
      captured
      email
      contact
      notes
      fee
      tax
      errorCode
      errorDescription
      refundStatus
      description
    }
  }
}
