query paymentMethods(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
  $active: Boolean
  $type: String
) {
  paymentMethods(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    active: $active
    store: $store
    type: $type
  ) {
    count
    page
    pageSize
    data {
      id
      name
      img
      imgCdn
      value
      color
      key
      text
      qrcode
      type
      instructions
      position
      active
    }
  }
}
