query importDetails(
  $type: String!
  $page: Int
  $limit: Int
  $search: String
  $sort: String
) {
  importDetails(
    type: $type
    page: $page
    search: $search
    limit: $limit
    sort: $sort
  ) {
    count
    pageSize
    page
    data {
      id
      importNo
      rawNo
      totalItems
      message
      fileName
      type
      success
      user
    }
  }
}
