query bannerGroup(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $type: String
  $pageId: String
  $active: Boolean
  $groupId: String!
  $store: ID
) {
  bannerGroup(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    type: $type
    pageId: $pageId
    active: $active
    groupId: $groupId
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      link
      heading
      img
      sort
      type
      store
      pageId
      active
      groupId
      groupTitle
      createdAt
      updatedAt
    }
  }
}
