query banners(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $type: String
  $pageId: String
  $active: Boolean
) {
  banners(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    type: $type
    pageId: $pageId
    active: $active
  ) {
    count
    page
    pageSize
    data {
      id
      link
      heading
      img
      sort
      type
      pageId
      active
      createdAt
      updatedAt
    }
  }
}
