mutation saveBanner(
  $id: String!
  $link: String
  $heading: String
  $img: String
  $sort: Int
  $type: String
  $active: Boolean
) {
  saveBanner(
    id: $id
    link: $link
    heading: $heading
    img: $img
    sort: $sort
    type: $type
    active: $active
  ) {
    id
    link
    heading
    img
    sort
    type
    active
    createdAt
    updatedAt
  }
}
