mutation saveBanner(
  $id: String!
  $link: String
  $heading: String
  $img: String
  $sort: Int
  $type: String
  $pageId: String
  $active: Boolean
  $groupId: String
  $groupTitle: String
) {
  saveBanner(
    id: $id
    link: $link
    heading: $heading
    img: $img
    sort: $sort
    type: $type
    pageId: $pageId
    active: $active
    groupId: $groupId
    groupTitle: $groupTitle
  ) {
    id
    link
    heading
    img
    sort
    type
    pageId
    active
    groupId
    groupTitle
    createdAt
    updatedAt
  }
}


# {
#   "id":"new",
#   "img":"img2.com",
#   "groupId":"11",
#   "groupTitle":"trending in indian"
# }