mutation saveAttribute(
  $id: String
  $category: ID
  $name: String
  $show: Boolean
  $active: Boolean
) {
  saveAttribute(
    id: $id
    category: $category
    name: $name
    show: $show
    active: $active
  ) {
    id
    name
    show
    category
    active
    createdAt
    updatedAt
  }
}
