mutation saveColor(
  $id: String
  $name: String!
  $slug: String
  $img: String
  $position: Int
  $featured: Boolean
  $meta: String
  $metaTitle: String
  $metaDescription: String
  $metaKeywords: String
  $active: Boolean
) {
  saveColor(
    id: $id
    name: $name
    slug: $slug
    featured: $featured
    active: $active
  ) {
    id
    name
    slug
    val
    value
    info
    featured
    active
    featured
    createdAt
    updatedAt
  }
}
