query sizes($page: Int, $search: String, $limit: Int, $sort: String) {
  sizes(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      slug
      info
      img
      featured
      active
      createdAt
      updatedAt
    }
  }
}
