mutation saveBrand(
  $id: String
  $brand_id: String
  $name: String
  $slug: String
  $parent: ID
  $img: String
  $position: Int
  $featured: Boolean
  $meta: String
  $metaTitle: String
  $metaDescription: String
  $metaKeywords: String
  $active: Boolean
) {
  saveBrand(
    id: $id
    brand_id: $brand_id
    name: $name
    slug: $slug
    parent: $parent
    img: $img
    position: $position
    meta: $meta
    metaTitle: $metaTitle
    metaDescription: $metaDescription
    metaKeywords: $metaKeywords
    featured: $featured
    active: $active
  ) {
    id
    brand_id
    name
    slug
    img
    meta
    metaTitle
    metaDescription
    metaKeywords
    featured
    active
    createdAt
    updatedAt
  }
}
