query popularSearches($page: Int, $limit: Int, $search: String, $sort: String) {
  popularSearches(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      text
      popularity
    }
  }
}
