mutation addToCart(
  $qty: Int!
  $pid: ID!
  $vid: ID
  $options: String
  $vendor: ID
  $replace: Boolean
  $optionValues: [ID]
) {
  addToCart(
    qty: $qty
    pid: $pid
    vid: $vid
    options: $options
    vendor: $vendor
    replace: $replace
    optionValues: $optionValues
  ) {
    items {
      pid
      vid
      barcode
      name
      type
      slug
      qty
      price
      shippingCharge
      tax
      img
      imgCdn
      options
      brandName
      vendor
      vendorSlug
      vendorBusinessName
      deliveryDetails
    }
    needAddress
    qty
    subtotal
    discount {
      code
      value
      text
      amount
    }
    shipping {
      charge
    }
    tax
    total
  }
}

# for multiple vendor in futute
# {
#   "options": "null",
#   "pid": "61bb679cae9d890438612b83",
#   "qty":1,
#   "vid": "61bb679cae9d890438612b83",
#   "optionValues": "61bb7174aa5a773af4b5da98"
# }
