# , $options:String
mutation checkout($address: ID!, $paymentMethod: String) {
  # , options:$options
  checkout(address: $address, paymentMethod: $paymentMethod) {
    id
    orderNo
    otp
    amount {
      qty
      subtotal
      discount
      shipping
      total
    }
    payment_order_id
    delivery {
      otp
    }
    items {
      status
      pid
      name
      slug
      img
      tracking
      vendor {
        id
        firstName
        lastName
        phone
      }
    }
    address {
      firstName
      lastName
      phone
    }
    user {
      id
      firstName
      lastName
      phone
    }
    createdAt
    updatedAt
  }
}

# {
#   "address": "6056394384f1ac2c5cc255d1",
#   "paymentMethod": "cod"
# }
