# , $options:String
mutation checkout($address: ID!, $paymentMethod: String) {
  # , options:$options
  checkout(address: $address, paymentMethod: $paymentMethod) {
    id
    orderNo
    otp
    amount {
      qty
      subtotal
      discount
      shipping
      total
    }
    paymentOrderId
    paymentMode
    paymentAmount
    paymentCurrency
    paymentTxStatus
    paymentReferenceId
    delivery {
      otp
    }
    items {
      status
      pid
      name
      slug
      img
      tracking
      vendor {
        id
        firstName
        lastName
        phone
      }
    }
    address {
      firstName
      lastName
      phone
    }
    user {
      id
      firstName
      lastName
      phone
    }
    createdAt
    updatedAt
  }
}

# for multiple vendor in futute
# {
#   "address": "607731ed83429404649a859f",
#   "paymentMethod": "cod"
#   "pid": "60151b263101e96f152d5165",
#   "qty": 1
# }
