query deals(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  deals(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      img
      imgCdn
      startTime
      endTime
      startTimeISO
      endTimeISO
      onGoing
      dealStatus
      active
      products {
        id
        sku
        barcode
        productMasterId
        slug
        name
        description
        type
        price
        mrp
        hasStock
        isUnlimited
        stock
        tax
        img
        imgCdn
        images
        imagesCdn
        time
        active
        popularity
        position
        trending
        featured
        hot
        new
        sale
        recommended
        title
        metaDescription
        keywords
        ratings
        reviews
        itemId
        warranty
        # discountPercent
        ageMin
        ageMax
        ageUnit
        cgst
        sgst
        igst
        returnInfo
        returnAllowed
        replaceAllowed
        returnValidityInDays
        isSearchable
        formattedMrp
        formattedPrice
      }
      store {
        id
        name
        email
      }
    }
  }
}
