mutation saveDeal(
  $id: ID
  $name: String
  $description: String
  $img: String
  $startTime: String
  $endTime: String
  $startTimeISO: String
  $endTimeISO: String
  $onGoing: Boolean
  $products: [String]
  $dealStatus: Boolean
  $active: Boolean
  $store: ID
) {
  saveDeal(
    id: $id
    name: $name
    description: $description
    img: $img
    startTime: $startTime
    endTime: $endTime
    startTimeISO: $startTimeISO
    endTimeISO: $endTimeISO
    onGoing: $onGoing
    products: $products
    dealStatus: $dealStatus
    active: $active
    store: $store
  ) {
    id
    name
    description
    img
    imgCdn
    startTime
    endTime
    startTimeISO
    endTimeISO
    onGoing
    dealStatus
    active
    products
    store
  }
}

# {
#   "id": "new",
# "endTime": "2022-03-23T05:42:37.316Z",
# "img": "https://misiki.s3.ap-south-1.amazonaws.com/stores/613ecab0f4444b321ee30346/deals/pj_logo-yxrk2djdknnp.jpg",
# "name": "test ",
# "onGoing": false,
# "startTime": "2022-03-25T05:42:37.316Z",
#   "dealStatus": true
# }
