mutation saveEvent($id: String!, $rules: [ruleIp], $active: Boolean) {
  saveEvent(id: $id, rules: $rules, active: $active) {
    id
    active
    rules {
      enable
      day
      intervals {
        from
        to
      }
    }
  }
}

# {
#   "id": "new",
#   "rules": [{
#     "day": "sunday",
#     "intervals": [{
#       "from": "09:00",
#       "to": "10:00"
#     },{
#       "from": "10:00",
#       "to": "11:00"
#     }]
#   },{
#     "day": "monday",
#     "intervals": [{
#       "from": "09:00",
#       "to": "10:00"
#     },{
#       "from": "10:00",
#       "to": "11:00"
#     }]
#   }]
# }
