query stores(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $active: Boolean
) {
  stores(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    active: $active
  ) {
    count
    page
    pageSize
    data {
      id
      active
      featured
      adminNotifications {
        lowStockNotification
        newOrderPlaced
      }
      address
      alert
      analyticsTrackingId
      banners
      closed
      closedMessage
      customerOrderNotifications {
        downloadEGoods
        giftCardPurchased
        orderConfirmation
        orderIsReadyForPickup
        orderShipped
        orderStatusChanged
      }
      description
      metaDescription
      dimentionUnit
      domain
      email
      facebook
      facebookPixelId
      facebookUrl
      favicon
      faviconCdn
      firstName
      freeShippingOn
      gdpr
      gdprCookieConsent
      google
      googleAdsTag
      homeMeta1
      homeMeta2
      homeMeta3
      homeMeta4
      img
      imgCdn
      images
      imagesCdn
      instagram
      instagramUrl
      isHideNilStock
      isMegamenu
      isOpen
      isSearch
      isWishlist
      isCart
      keywords
      lastName
      lat
      legalName
      linkedin
      lng
      locality
      logo
      logoCdn
      logoDark
      logoDarkCdn
      logoMobile
      logoMobileCdn
      logoMobileDark
      logoMobileDarkCdn
      minimumOrderValue
      minOrderValue
      name
      openGraphImage
      openGraphImageCdn
      pageSize
      phone
      pinterestTag
      pinterestUrl
      qrCode
      review {
        enabled
        moderate
      }
      searchbarText
      shipping {
        charge
        deliveryDays
        enabled
        free
        method
        provider
      }
      shippingCharge
      shopAddress
      shopPhone
      slug
      snapChatPixel
      state
      storeId
      timeZone
      timing
      title
      twitter
      twitterUrl
      websiteEmail
      websiteLegalName
      websiteName
      weightUnit
      youtubeUrl
      zip
      timeDisplayFormat
      priceDisplayFormat
      createdAt
      updatedAt
      totalProducts
      lastAddedProduct {
        id
        name
        stock
        img
        imgCdn
      }
      user {
        firstName
        lastName
        email
        phone
      }
    }
  }
}
