query store {
  store {
    id
    active
    address
    analyticsTrackingId
    banners
    city
    country
    currency
    currencyCode
    currencySymbol
    dimentionUnit
    email
    facebookPixelId
    facebookUrl
    freeShippingOn
    gdprCookieConsent
    googleAdsTag
    img
    instagramUrl
    isHideNilStock
    isOpen
    legalName
    minOrderValue
    name
    phone
    pinterestTag
    pinterestUrl
    shippingCharge
    slug
    snapChatPixel
    state
    storeId
    timeZone
    twitterUrl
    weightUnit
    youtubeUrl
    zip
    createdAt
    updatedAt
    user {
      firstName
      lastName
      email
      phone
    }
  }
}
