query settings {
  settings {
    id
    websiteName
    closed
    closedMessage
    minimumOrderValue
    title
    alert
    keywords
    description
    tax {
      cgst
      sgst
      igst
    }
    demo
    RAZORPAY_KEY_ID
    stripePublishableKey
    enableStripe
    enableRazorpay
    currency_code
    currency_symbol
    currency_decimals
    open_graph_image
    shipping {
      delivery_days
      charge
      free
      method
    }
    userRoles
    websiteEmail
    shopPhone
    shopAddress
    logo
    logoMobile
    logoDark
    logoMobileDark
    favicon
    CDN_URL
    searchbar_text
    adminPanelLink
    pageSize
    orderStatuses {
      status
      title
      body
      icon
      public
      index
    }
    paymentStatuses
    otpLogin
    sms {
      AUTO_VERIFICATION_ID
      enabled
      provider
    }
    email {
      enabled
      from
      cc
      bcc
      printers
    }
    storage {
      enabled
      provider
    }
    review {
      enabled
      moderate
    }
    product {
      moderate
    }
    GOOGLE_MAPS_API
    facebook
    twitter
    google
    instagram
    enableTax
    locationExpiry
  }
}
