mutation cashfreePayNowSubscription($subscription: ID!, $intervalType: String) {
  cashfreePayNowSubscription(
    subscription: $subscription
    intervalType: $intervalType
  ) {
    appId
    orderId
    orderAmount
    orderCurrency
    orderNote
    customerName
    customerEmail
    customerPhone
    returnUrl
    notifyUrl
    signature
    token
    url
    stage
  }
}

# intervalType: year or month(default)
