mutation cashfreeSubscription($subscription: ID!, $intervalType: String!) {
  cashfreeSubscription(
    subscription: $subscription
    intervalType: $intervalType
  ) {
    id
    paymentReferenceId
    authLink
  }
}

# intervalType: year or month

# {
#   "subscription": "61b078664332fe348055032d",
#   "intervalType": "month"
# }
