mutation stripeSubscription($subscription: ID!, $intervalType: String) {
  stripeSubscription(subscription: $subscription, intervalType: $intervalType) {
    id
    paymentReferenceId
  }
}

# intervalType: year or month(default)

# {
#   "subscription": "61b078664332fe348055032d",
#   "intervalType": "month"
# }
