mutation {
  updateAddress(id: "5ff57afbb04e9227946d32aa", active: false, state: "raj") {
    id
    type
    active
    firstName
    lastName
    type
    address
    town
    district
    city
    state
    country
    state
    zip
    phone
    user
  }
}
