mutation saveWebhook(
  $id: String!
  $url: String
  $name: String
  $description: String
  $events: [String!]
  $sort: Float
  $active: Boolean
  $store: ID
) {
  saveWebhook(
    id: $id
    url: $url
    name: $name
    description: $description
    events: $events
    sort: $sort
    active: $active
    store: $store
  ) {
    id
    url
    name
    description
    events
    sort
    active
    store
    createdAt
    updatedAt
  }
}

# {
#   "id": "62ac109abca1822c6474a6a7",
#   "url": "some",
#   "name":"Some name",
#   "description": "",
#   "active": true,
#   "events": [
#     "order.created",
#     "subscription.created"
#   ],
#   "store": "60fb92e49f73050d30287cae"
# }
