query webhook1($id: ID!) {
  webhook1(id: $id) {
    id
    url
    name
    description
    events
    sort
    active
    store
    createdAt
    updatedAt
  }
}

# {
#   "id":"62ac0f6592dd6e4828190e9a"
# }
