query storeCountry($id: ID!) {
  storeCountry(id: $id) {
    id
    default
    active
    country {
      id
      name
      value
      dialCode
      code
      img
      imgCdn
      flag
      lang
    }
    user {
      id
      firstName
      lastName
    }
  }
}
