mutation saveStoreLanguage(
  $id: String!
  $lang: ID
  $default: Boolean
  $active: Boolean
) {
  saveStoreLanguage(id: $id, lang: $lang, default: $default, active: $active) {
    id
    default
    active
    name
    code
    lang
    user
    store
  }
}
