query storeLanguages(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID!
) {
  storeLanguages(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      default
      active
      lang {
        id
        name
        nativeName
        code
        phpLocaleCode
        rtl
        sort
        active
        createdAt
        updatedAt
      }
      user {
        id
        firstName
        lastName
        email
      }
    }
  }
}
