mutation saveReview(
  $id: String!
  $pid: ID
  $variant: ID
  $user: ID
  $rating: Int
  $message: String
  $active: Boolean
) {
  saveReview(
    id: $id
    pid: $pid
    variant: $variant
    user: $user
    rating: $rating
    message: $message
    active: $active
  ) {
    id
    pid {
      name
      slug
      img
      type
    }
    user {
      firstName
      lastName
      phone
    }
    rating
    message
    active
  }
}
