query referral($id: ID!) {
  referral(id: $id) {
    id
    storeCreated
    subscriptionBought
    subscribe {
      id
    }
    referredFrom {
      id
      email
    }
    referredTo {
      id
      email
    }
  }
}
