mutation saveSubscription(
  $id: String!
  $name: String
  $img: String
  $mrp: Int
  $price: Int
  $days: Int
  $sort: Int
  $active: Boolean
) {
  saveSubscription(
    id: $id
    name: $name
    img: $img
    mrp: $mrp
    price: $price
    days: $days
    sort: $sort
    active: $active
  ) {
    id
    name
    img
    mrp
    price
    sort
    days
    active
  }
}

# {
#   "id": "60b62c4815ff1f158c9c6f39",
#   "name": "prime",
#   "mrp": 297,
#   "price": 247,
#   "days": 36
# }
