mutation saveSubscription(
  $id: String!
  $abandonnedCartRecovery: Boolean
  $active: Boolean
  $annualPrice: Float
  $chatSupport: Boolean
  $customDomain: Boolean
  $description: String
  $discountCoupons: Boolean
  $emailSupport: Boolean
  $freeSSL: Boolean
  $misReports: Boolean
  $monthlyPrice: Float
  $name: String
  $onlineStore: Boolean
  $premiumSupport: Boolean
  $productImportExport: Boolean
  $productsAllowed: Int
  $removeMisikiLogo: Boolean
  $salesChannels: Boolean
  $seoOptions: Boolean
  $title: String
  $transactionFees: Float
  $transactionFeesType: String
  $unlimitedProducts: Boolean
  $unlimitedValidity: Boolean
  $maxAdminAllowed: Int
  $cashfreePlanId: String
  $stripePlanId: String
  $photosAllowed: Int
  $callMeLimit: Int
  $homepageAdvertise: String
  $expertConsultation: String
  $pickup: Boolean
  $delivery: Boolean
  $tableBooking: Boolean
  $appointments: Boolean
) {
  saveSubscription(
    id: $id
    abandonnedCartRecovery: $abandonnedCartRecovery
    active: $active
    annualPrice: $annualPrice
    chatSupport: $chatSupport
    customDomain: $customDomain
    description: $description
    discountCoupons: $discountCoupons
    emailSupport: $emailSupport
    freeSSL: $freeSSL
    misReports: $misReports
    monthlyPrice: $monthlyPrice
    name: $name
    onlineStore: $onlineStore
    premiumSupport: $premiumSupport
    productImportExport: $productImportExport
    productsAllowed: $productsAllowed
    removeMisikiLogo: $removeMisikiLogo
    salesChannels: $salesChannels
    seoOptions: $seoOptions
    title: $title
    transactionFees: $transactionFees
    transactionFeesType: $transactionFeesType
    unlimitedProducts: $unlimitedProducts
    unlimitedValidity: $unlimitedValidity
    maxAdminAllowed: $maxAdminAllowed
    cashfreePlanId: $cashfreePlanId
    stripePlanId: $stripePlanId
    photosAllowed: $photosAllowed
    callMeLimit: $callMeLimit
    homepageAdvertise: $homepageAdvertise
    expertConsultation: $expertConsultation
    pickup: $pickup
    delivery: $delivery
    tableBooking: $tableBooking
    appointments: $appointments
  ) {
    id
    name
    abandonnedCartRecovery
    active
    annualPrice
    chatSupport
    customDomain
    description
    discountCoupons
    emailSupport
    freeSSL
    misReports
    monthlyPrice
    name
    onlineStore
    premiumSupport
    productImportExport
    productsAllowed
    removeMisikiLogo
    salesChannels
    seoOptions
    title
    transactionFees
    transactionFeesType
    unlimitedProducts
    unlimitedValidity
    maxAdminAllowed
    cashfreePlanId
    stripePlanId
    photosAllowed
    callMeLimit
    homepageAdvertise
    expertConsultation
    pickup
    delivery
    tableBooking
    appointments
    createdAt
    updatedAt
  }
}
