query subscriptions {
  subscriptions {
    count
    page
    data {
      id
      name
      type
      img
      mrp
      price
      days
      active
      vendor {
        firstName
        lastName
      }
    }
  }
}
