query subscription($id: ID!) {
  subscription(id: $id) {
    id
    name
    abandonnedCartRecovery
    active
    annualPrice
    chatSupport
    customDomain
    description
    discountCoupons
    emailSupport
    freeSSL
    misReports
    monthlyPrice
    name
    onlineStore
    premiumSupport
    productImportExport
    productsAllowed
    removeMisikiLogo
    salesChannels
    seoOptions
    title
    transactionFees
    transactionFeesType
    unlimitedProducts
    unlimitedValidity
    maxAdminAllowed
    cashfreePlanId
    stripePlanId
    photosAllowed
    callMeLimit
    homepageAdvertise
    expertConsultation
    createdAt
    updatedAt
  }
}
