query collections($page: Int, $search: String, $limit: Int, $sort: String) {
  collections(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      description
      active
      images
      img
      q
      sort
      type
      products {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}
