query option($id: ID!) {
  option(id: $id) {
    id
    name
    inputType
    preselectDefault
    position
    required
    values {
      id
      name
      default
      position
      direction
      isPercent
      value
    }
  }
}
