query options($product: ID!) {
  options(product: $product) {
    count
    page
    pageSize
    data {
      id
      name
      inputType
      preselectDefault
      position
      values {
        id
        name
        default
        position
        direction
        isPercent
        value
      }
    }
  }
}
