mutation saveOption(
  $id: String!
  $pid: ID
  $name: String
  $key: String
  $val: String
  $categories: [String]
  $position: Int
  $slug: String
  $isFilter: Boolean
  $preselect: Boolean
  $required: Boolean
  $type: String
  $info: String
  $active: Boolean
) {
  saveOption(
    id: $id
    pid: $pid
    name: $name
    key: $key
    val: $val
    categories: $categories
    position: $position
    slug: $slug
    isFilter: $isFilter
    info: $info
    preselect: $preselect
    required: $required
    type: $type
    active: $active
  ) {
    id
    pid
    name
    key
    val
    categories
    position
    slug
    info
    preselect
    required
    type
    isFilter
    active
    values {
      id
      name
      default
      slug
      position
      direction
      type
      amount
    }
  }
}

# {
#   "id": "new",
#   "pid": "60151b263101e96f152d5157",
#   "name": "color2",
#   "type": "text field"
# }
