mutation saveOption(
  $id: String
  $name: String
  $inputType: String
  $preselectDefault: Boolean
  $required: Boolean
  $position: Int
  $product: ID
) {
  saveOption(
    id: $id
    name: $name
    inputType: $inputType
    preselectDefault: $preselectDefault
    required: $required
    position: $position
    product: $product
  ) {
    id
    name
    inputType
    preselectDefault
    required
    position
    product
  }
}

# {
#   "id": "new",
#   "name": "gift wrap",
#  "product": "61bb46b0038cf5356c863e9e"
# }
