query HOME($store: ID) {
  dailySales {
    _id
    total
    qty
  }
  topVendors {
    id
    firstName
    lastName
    productSold
    avatar
    avatarCdn
  }
  userSummary {
    count
  }
  productSummary {
    count
  }
  categorySummary {
    count
  }
  orderSummary {
    count
    amount
  }
  paymentsSummary {
    count
    amount
  }
  vendorSummary {
    _id
    count
    amount
    createdAt
    codPaid
  }
  statusSummary {
    _id
    count
    amount
  }
  byVendor {
    count
    pageSize
    page
    data {
      _id {
        vendor {
          firstName
          lastName
          phone
        }
      }
      date
      items {
        pid
        name
      }
      total
      count
    }
  }
  myOrderItems(store: $store) {
    count
    pageSize
    page
    data {
      id
      status
      pid
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      imgCdn
      tracking
      shippingCharge
      price
      qty
      tax
      brandName
      brandImg
      brandImgCdn
      size
      color
      trackingId
      returnTrackingId
      courierName
      returnCourierName
      #order level info
      orderNo
      otp
      createdAt
      paySuccess
      payment {
        id
      }
      paymentMode
      paymentStatus
      paymentCurrency
      paymentReferenceId
      paymentOrderId
      paymentReceipt
      invoiceId
      paymentGateway
      codPaid
      amountPaid
      amountDue
      paymentMsg
      paymentTime
      paid
      userFirstName
      userLastName
      userPhone
      invoiceLink
      returnValidTill
      paymentMode
      paymentAmount
      user {
        firstName
        lastName
        email
        phone
        role
      }
      address {
        firstName
        lastName
        address
        lat
        lng
      }
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      payment {
        amountPaid
        amountDue
      }
      store {
        id
        name
        email
      }
      orderHistory {
        id
        status
        title
        body
        icon
        public
        index
        time
      }
    }
  }
}
