query category($id: String, $slug: String) {
  category(id: $id, slug: $slug) {
    id
    name
    parent
    children {
      id
      name
      img
    }
    slug
    img
    level
    metaTitle
    metaDescription
    metaKeywords
    position
    megamenu
    active
    featured
    createdAt
    updatedAt
  }
}
