query {
  categories {
    data {
      id
      index
      name
      slug
      path
      slugPath
      namePath
      level
      position
      megamenu
      meta
      metaTitle
      metaDescription
      metaKeywords
      img
      featured
      shopbycategory

      parent {
        id
      }
      count
      sizechart
      active
      createdAt
      updatedAt
    }
  }
}
