query categories(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $megamenu: Boolean
  $featured: Boolean
  $active: Boolean
  $img: Boolean
  $shopbycategory: Boolean
) {
  categories(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    megamenu: $megamenu
    featured: $featured
    active: $active
    img: $img
    shopbycategory: $shopbycategory
  ) {
    count
    page
    pageSize
    data {
      id
      name
      namePath
      categoryId
      parent
      slug
      img
      level
      metaTitle
      metaDescription
      metaKeywords
      position
      megamenu
      active
      featured
      shopbycategory
      createdAt
      updatedAt
    }
  }
}
