query megamenu(
  $id: ID
  $slug: String
  $search: String
  $sort: String
  $featured: Boolean
  $brands: [ID]
) {
  megamenu(
    id: $id
    slug: $slug
    search: $search
    sort: $sort
    featured: $featured
    brands: $brands
  ) {
    id
    name
    slug
    img
    featured
    children {
      name
      slug
      img
      featured
      children {
        name
        slug
        img
        featured
        children {
          name
          slug
          img
          featured
          children {
            name
            slug
            img
            featured
            children {
              name
              slug
              img
              featured
              children {
                name
                slug
                img
                featured
                children {
                  name
                  slug
                  img
                  featured
                  children {
                    name
                    slug
                    img
                    featured
                    children {
                      name
                      slug
                      img
                      featured
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}


# {
#   "brands": ["60b4d95b1515460f94e58d4f"]
# }
