query megamenuAll($id: ID, $search: String, $sort: String, $featured: Boolean) {
  megamenuAll(id: $id, search: $search, sort: $sort, featured: $featured) {
    id
    name
    slug
    img
    featured
    children {
      id
      name
      slug
      img
      featured
      children {
        id
        name
        slug
        img
        featured
        children {
          id
          name
          slug
          img
          featured
          children {
            id
            name
            slug
            img
            featured
            children {
              id
              name
              slug
              img
              featured
              children {
                id
                name
                slug
                img
                featured
                children {
                  id
                  name
                  slug
                  img
                  featured
                  children {
                    id
                    name
                    slug
                    img
                    featured
                    children {
                      id
                      name
                      slug
                      img
                      featured
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
