query megamenuAll($id: ID, $search: String, $sort: String, $featured: Boolean) {
  megamenuAll(id: $id, search: $search, sort: $sort, featured: $featured) {
    id
    name
    slug
    img
    featured
    parent {
      id
    }
    attributes {
      id
      name
      show
      category
      active
    }
    children {
      id
      name
      slug
      img
      featured
      parent {
        id
      }
      attributes {
        id
        name
        show
        category
        active
      }
      children {
        id
        name
        slug
        img
        featured
        parent {
          id
        }
        attributes {
          id
          name
          show
          category
          active
        }
        children {
          id
          name
          slug
          img
          featured
          parent {
            id
          }
          attributes {
            id
            name
            show
            category
            active
          }
          children {
            id
            name
            slug
            img
            featured
            parent {
              id
            }
            attributes {
              id
              name
              show
              category
              active
            }
            children {
              id
              name
              slug
              img
              featured
              parent {
                id
              }
              attributes {
                id
                name
                show
                category
                active
              }
              children {
                id
                name
                slug
                img
                featured
                parent {
                  id
                }
                attributes {
                  id
                  name
                  show
                  category
                  active
                }
                children {
                  id
                  name
                  slug
                  img
                  featured
                  parent {
                    id
                  }
                  attributes {
                    id
                    name
                    show
                    category
                    active
                  }
                  children {
                    id
                    name
                    slug
                    img
                    featured
                    parent {
                      id
                    }
                    attributes {
                      id
                      name
                      show
                      category
                      active
                    }
                    children {
                      id
                      name
                      slug
                      img
                      featured
                      parent {
                        id
                      }
                      attributes {
                        id
                        name
                        show
                        category
                        active
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
