mutation {
  saveCategory(
    name: "Electronics"
    parent: "5d3c40f41699ca065e5256f2"
    slug: "electronics"
    img: "https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
    level: 0
    metaTitle: "electri"
    position: 0
    megamenu: false
    featured: true
    active: true
    shopbycategory: true
    id: "new"
  ) {
    id
    index
    name
    slug
    path
    slugPath
    namePath
    level
    position
    megamenu
    meta
    metaTitle
    metaDescription
    metaKeywords
    img
    featured
    shopbycategory
    children {
      id
      name
    }
    count
    sizechart
    active
    createdAt
    updatedAt
  }
}
