query popular($store: ID, $page: Int) {
  popular(store: $store, page: $page) {
    data {
      id
      slug
      name
      type
      price
      stock
      img
      imgCdn
      images
      imagesCdn
      time
      ratings
      reviews
      vendor {
        id
        firstName
        lastName
        phone
        email
        info {
          store
          storePhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
