query popular($store: ID, $page: Int, $zip: String) {
  popular(store: $store, page: $page, zip: $zip) {
    data {
      id
      slug
      name
      type
      price
      mrp
      stock
      img
      imgCdn
      images
      imagesCdn
      time
      ratings
      reviews
      zips
      vendor {
        id
        slug
        businessName
        banner
        bannerCdn
        ratings
        reviews
        info {
          store
          public
          storePhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
