query product($id: ID!) {
  product(id: $id) {
    id
    slug
    name
    description
    type
    price
    mrp
    stock
    tax
    img
    images
    time
    active
    popularity
    position
    sku
    hsn
    group
    barcode
    gender
    gtin
    condition
    trending
    featured
    hot
    new
    sale
    recommended
    title
    itemId
    warranty
    metaDescription
    keywords
    discountPercent
    ageMin
    ageMax
    ageUnit
    styleCode
    eanNo
    articleCode
    productMasterId
    currency
    manufacturer
    countryOfOrigin
    returnInfo
    link
    gender
    condition
    gtin
    cgst
    sgst
    igst
    sizeGroup {
      _id
      slug
      size {
        name
      }
    }
    colorGroup {
      _id
      slug
      color {
        name
        color_code
      }
    }
    brand {
      id
      name
    }
    color {
      id
      name
    }
    size {
      id
      name
    }
    category {
      id
      name
      slug
      pathA {
        name
        slug
      }
    }
    categories {
      id
      name
    }
    categoryPool {
      id
      name
    }
    keyFeatures
    features {
      id
      name
      value
    }
    productDetails {
      id
      name
      value
    }
    liveStreams {
      id
      title
      imageUrl
      scheduleDateTime
      user
    }
    options {
      id
      name
      type
      default_option
      values {
        id
        name
        default
      }
    }
    variants {
      id
      options {
        name
        val
      }
      stock
      weight
      length
      width
      height
      barcode
      sku
      mrp
      price
      images
      trackInventory
      active
      sort
    }
    vendor {
      id
      firstName
      lastName
      phone
      email
      address {
        address
      }
      info {
        store
        storePhotos
      }
    }
    relatedProducts {
      id
      name
      slug
      img
    }
    returnInfo
  }
}
