query product1($id: ID!) {
  product1(id: $id) {
    id
    slug
    name
    description
    type
    price
    mrp
    stock
    tax
    img
    images
    time
    active
    popularity
    position
    sku
    hsn
    group
    barcode
    gender
    gtin
    condition
    itemId
    warranty
    trending
    featured
    hot
    new
    sale
    recommended
    title
    metaDescription
    keywords
    itemId
    warranty
    ageMin
    ageMax
    ageUnit
    styleCode
    eanNo
    articleCode
    productMasterId
    currency
    manufacturer
    countryOfOrigin
    returnInfo
    link
    gender
    condition
    gtin
    cgst
    sgst
    igst
    keyFeatures
    returnInfo
    brand
    color
    size
    features
    productDetails
    liveStreams
    category
    categories
    categoryPool
    variants {
      id
      options {
        name
        val
      }
      stock
      weight
      barcode
      sku
      mrp
      price
      images
      trackInventory
      active
      sort
    }
    options {
      id
      name
      type
      position
      preselect
      active
      required
      default_option
      values {
        id
        name
        position
        amount
        direction
        default
      }
    }
    vendor
    relatedProducts
  }
}
