query products(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $vendor: String
  $category: String
  $active: Boolean
  $featured: Boolean
  $new: Boolean
  $hot: Boolean
  $sale: Boolean
) {
  products(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    vendor: $vendor
    category: $category
    active: $active
    featured: $featured
    new: $new
    hot: $hot
    sale: $sale
  ) {
    count
    data {
      id
      slug
      name
      type
      price
      mrp
      stock
      img
      images
      time
      active
      popularity
      position
      variants {
        id
        name
        options {
          name
        }
        stock
        weight
        barcode
        sku
        mrp
        price
        images
        trackInventory
        active
        sort
      }
      trending
      featured
      hot
      new
      sale
      recommended
      title
      metaDescription
      keywords
      ratings
      reviews
      category {
        name
      }
      vendor {
        id
        firstName
        lastName
        phone
        email
        address {
          address
        }
        info {
          store
          storePhotos
        }
      }
    }
    count
    pageSize
    noOfPage
    page
  }
}
