query productSlug($slug: String!) {
  productSlug(slug: $slug) {
    id
    name
    slug
    img
    imgCdn
    images
    imagesCdn
    price
    stock
    trackInventory
    ratings
    reviews
    vendor {
      id
      slug
      businessName
      banner
      bannerCdn
      ratings
      reviews
      info {
        store
        public
        storePhotos
      }
    }
  }
}
