query productsByIds($ids: [ID!]) {
  productsByIds(ids: $ids) {
    id
    name
    slug
    img
    imgCdn
    price
    stock
    ratings
    reviews
    vendor {
      id
      slug
      businessName
      banner
      bannerCdn
      ratings
      reviews
      info {
        store
        public
        storePhotos
      }
    }
  }
}
