query {
  product(id: "5fdc4f5fd93e5e0018dcb6b0") {
    id
    name
    description
    slug
    img
    img_featured
    images
    variants {
      id
      name
    }
    enableZips
    zips
    category {
      id
      name
    }
    brand {
      id
      name
    }
    parentCategory {
      id
      name
    }

    status
    type
    city
    stock
    price
    time
    daily
    features
    vendor {
      id
      firstName
    }
    active
    info
    title
    metaDescription
    keywords
    position
    popularity
    trending
    featured
    hot
    new
    sale
    recommended
    hsn
    barcode
    group
    sku
    color
    sales
    ratings
    reviews
    approved

    createdAt
    updatedAt
  }
}
