mutation saveProduct(
  $id: String!
  $name: String
  $description: String
  $type: String
  $city: String
  $price: Float
  $mrp: Float
  $stock: Int
  $tax: Float
  $img: String
  $images: [String]
  $time: String
  $active: Boolean
  $hot: Boolean
  $featured: Boolean
  $trending: Boolean
  $sale: Boolean
  $new: Boolean
  $recommended: Boolean
  $position: Int
  $category: ID
  $categories: [ID]
  $brand: ID
  $variants: [ID!]
  $popularity: Int
  $sku: String
  $hsn: String
  $group: String
  $color: ID
  $size: ID
  $barcode: String
  $title: String
  $metaDescription: String
  $keywords: String
  $itemId: String
  $warranty: String
  $age_min: Int
  $age_max: Int
  $age_unit: String
  $style_code: String
  $ean_no: String
  $article_code: String
  $product_master_id: String
  $currency: String
  $manufacturer: String
  $return_info: String
  $gender: String
  $condition: String
  $gtin: String
  $country_of_origin: String
  $cgst: Float
  $sgst: Float
  $igst: Float
) {
  saveProduct(
    id: $id
    name: $name
    description: $description
    type: $type
    city: $city
    price: $price
    mrp: $mrp
    stock: $stock
    tax: $tax
    img: $img
    images: $images
    time: $time
    active: $active
    category: $category
    categories: $categories
    brand: $brand
    popularity: $popularity
    sku: $sku
    hsn: $hsn
    barcode: $barcode
    group: $group
    color: $color
    size: $size
    position: $position
    variants: $variants
    hot: $hot
    featured: $featured
    trending: $trending
    sale: $sale
    new: $new
    recommended: $recommended
    title: $title
    metaDescription: $metaDescription
    keywords: $keywords
    itemId: $itemId
    warranty: $warranty
    age_min: $age_min
    age_max: $age_max
    age_unit: $age_unit
    style_code: $style_code
    ean_no: $ean_no
    article_code: $article_code
    product_master_id: $product_master_id
    currency: $currency
    manufacturer: $manufacturer
    return_info: $return_info
    gender: $gender
    condition: $condition
    gtin: $gtin
    country_of_origin: $country_of_origin
    cgst: $cgst
    sgst: $sgst
    igst: $igst
  ) {
    id
    name
    description
    slug
    type
    city
    price
    mrp
    stock
    tax
    img
    images
    time
    active
    popularity
    sku
    hsn
    group
    color
    size
    barcode
    position
    trending
    featured
    hot
    new
    sale
    recommended
    title
    metaDescription
    keywords
    brand
    itemId
    warranty
    age_min
    age_max
    age_unit
    style_code
    ean_no
    article_code
    product_master_id
    currency
    manufacturer
    country_of_origin
    return_info
    gender
    condition
    gtin
    cgst
    sgst
    igst
    color_group
    size_group
    category {
      id
      name
      slug
    }
    variants {
      options {
        name
      }
      stock
      weight
      barcode
      sku
      mrp
      price
      img
      sort
    }
  }
}
