mutation saveProduct(
  $id: String
  $name: String
  $description: String
  $type: String
  $city: String
  $price: Int
  $stock: Int
  $img: String
  $images: [String]
  $time: String
  $active: Boolean
  $position: Int
  $badge: BadgeI
  $category: ID
  $categories: [ID]
  $brand: ID
  $vendor: String
  $variants: [ID!]
  $popularity: Int
  $hsn: Int
  $title: String
  $metaDescription: String
  $keywords: String
) {
  saveProduct(
    id: $id
    name: $name
    description: $description
    type: $type
    city: $city
    price: $price
    stock: $stock
    img: $img
    images: $images
    time: $time
    active: $active
    vendor: $vendor
    category: $category
    categories: $categories
    brand: $brand
    popularity: $popularity
    hsn: $hsn
    position: $position
    variants: $variants
    badge: $badge
    title: $title
    metaDescription: $metaDescription
    keywords: $keywords
  ) {
    id
    name
    description
    slug
    type
    city
    price
    stock
    img
    images
    time
    active
    popularity
    hsn
    position
    variants {
      options {
        name
      }
      stock
      weight
      barcode
      sku
      mrp
      price
      img
      sort
    }
    badge {
      trending
      featured
      hot
      new
      sale
      recommended
    }
    title
    metaDescription
    keywords
    brand {
      id
      name
    }
    category {
      id
      name
    }
    vendor {
      id
      firstName
      lastName
      phone
      info {
        store
      }
    }
  }
}
