query search(
  $page: Int
  $skip: Int
  $limit: Int
  $type: String
  $location: ID
  $country: ID
  $search: String
  $sort: String
  $q: String
  $zip: Float
) {
  search(
    page: $page
    q: $q
    skip: $skip
    limit: $limit
    type: $type
    location: $location
    country: $country
    search: $search
    sort: $sort
    zip: $zip
  ) {
    data {
      id
      slug
      name
      type
      price
      stock
      img
      imgCdn
      time
      ratings
      reviews
      trending
      hot
      sale
      featured
      recommended
      new
      vendor {
        id
        firstName
        lastName
        phone
        email
        avatar
        info {
          store
          storePhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
