query trending($type: String) {
  trending(type: $type) {
    id
    sku
    barcode
    description
    productMasterId
    slug
    name
    type
    price
    mrp
    stock
    tax
    img
    images
    time
    active
    popularity
    position
    trending
    featured
    hot
    new
    sale
    recommended
    title
    metaDescription
    keywords
    ratings
    reviews
    itemId
    warranty
    discount
    ageMin
    ageMax
    ageUnit
    cgst
    sgst
    igst
    category
    variants
    vendor
  }
}
