query wishlists($page: Int, $search: String, $limit: Int, $sort: String) {
  wishlists(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      product {
        id
        name
        img
        price
        mrp
        brand {
          id
          name
          img
        }
      }
      variant {
        id
        name
      }
      user {
        id
        firstName
        lastName
      }
      active
      createdAt
      updatedAt
    }
  }
}
