mutation saveMyVendorInfo(
  $bankAccountNo: Float
  $bankName: String
  $bankIfsc: String
  $bankAccountHolderName: String
  $address: ID
) {
  saveMyVendorInfo(
    bankAccountNo: $bankAccountNo
    bankName: $bankName
    bankIfsc: $bankIfsc
    bankAccountHolderName: $bankAccountHolderName
    address: $address
  ) {
    id
    bankAccountNo
    bankName
    bankIfsc
    bankAccountHolderName
    createdAt
    updatedAt
    user
    store
    address
  }
}
