mutation saveMyVendorInfo(
  $bankAccountNo: Float
  $bankName: String
  $bankIfsc: String
  $bankAccountHolderName: String
  $banner: String
  $address: ID
) {
  saveMyVendorInfo(
    bankAccountNo: $bankAccountNo
    bankName: $bankName
    bankIfsc: $bankIfsc
    bankAccountHolderName: $bankAccountHolderName
    banner: $banner
    address: $address
  ) {
    id
    bankAccountNo
    bankName
    bankIfsc
    bankAccountHolderName
    banner
    bannerCdn
    createdAt
    updatedAt
    address {
      id
      address
      locality
      city
      state
      country
      zip
      lat
      lng
    }
  }
}
