query storeVendorInfo($store: ID!) {
  storeVendorInfo(store: $store) {
    count
    page
    pageSize
    data {
      id
      slug
      businessName
      bankAccountNo
      bankName
      bankIfsc
      bankAccountHolderName
      bankSwiftCode
      banner
      bannerCdn
      commissionType
      commissionValue
      zips
      freeShippingOn
      meta
      metaDescription
      metaKeywords
      metaTitle
      productSold
      ratings
      reviews
      shippingCharges
      storeName
      facebookUrl
      githubUrl
      googleUrl
      twitterUrl
      info {
        public
        store
        storePhotos
      }
      country {
        id
        name
      }
      user {
        id
        avatar
      }
      address {
        id
      }
      store {
        id
        name
        email
      }
      createdAt
      updatedAt
    }
  }
}
