query storeVendorInfo($store: ID!) {
  storeVendorInfo(store: $store) {
    count
    page
    pageSize
    data {
      id
      bankAccountNo
      bankName
      bankIfsc
      bankAccountHolderName
      banner
      bannerCdn
      createdAt
      updatedAt
      user {
        id
      }
      address {
        id
      }
      store {
        id
        name
        email
      }
    }
  }
}
