query vendorInfo1($id: ID) {
  vendorInfo1(id: $id) {
    id
    slug
    bankAccountNo
    bankName
    bankIfsc
    bankAccountHolderName
    bankSwiftCode
    banner
    bannerCdn
    commissionType
    commissionValue
    createdAt
    updatedAt
    zips
    country
    user
    address
    store
    businessName
    freeShippingOn
    meta
    metaDescription
    metaKeywords
    metaTitle
    productSold
    ratings
    reviews
    shippingCharges
    storeName
    facebookUrl
    githubUrl
    googleUrl
    twitterUrl
    info {
      public
      store
      storePhotos
    }
  }
}
