mutation vendorVerfication(
  $id: ID!
  $country: ID
  $zips: [Float]
  $zip: String
) {
  vendorVerfication(id: $id, country: $country, zips: $zips, zip: $zip) {
    id
    zips
    country
    createdAt
    updatedAt
  }
}
