query liveStreams {
  liveStreams {
    id
    product {
      id
    }
    products {
      id
      name
      img
      slug
      price
      mrp
    }
    scheduleDateTime
    title
    img
    user {
      id
    }
    users {
      id
    }
  }
}
