query liveStream($id: ID!) {
  liveStream(id: $id) {
    id
    product {
      id
    }
    products {
      id
      name
      img
      slug
      price
      mrp
    }
    scheduleDateTime
    title
    img
    user {
      id
    }
    users {
      id
    }
  }
}
