mutation saveLiveStream(
  $id: String!
  $product: ID
  $products: [ID]
  $scheduleDateTime: String
  $title: String
  $img: String
) {
  saveLiveStream(
    id: $id
    product: $product
    products: $products
    scheduleDateTime: $scheduleDateTime
    img: $img
    title: $title
  ) {
    id
    product {
      id
    }
    products {
      id
    }
    scheduleDateTime
    title
    img
    user {
      id
    }
    users {
      id
    }
  }
}
