mutation saveTag(
  $id: String!
  $name: String
  $slug: String
  $colorCode: String
  $active: Boolean
) {
  saveTag(
    id: $id
    name: $name
    slug: $slug
    colorCode: $colorCode
    active: $active
  ) {
    id
    name
    slug
    colorCode
    active
    user
    store
  }
}
