mutation saveTag(
  $id: String!
  $name: String
  $slug: String
  $colorCode: String
) {
  saveTag(id: $id, name: $name, slug: $slug, colorCode: $colorCode) {
    id
    name
    slug
    colorCode
    user
    store
  }
}
