query tag($id: ID!) {
  tag(id: $id) {
    id
    name
    slug
    colorCode
    createdAt
    updatedAt
    user {
      firstName
      lastName
      avatar
    }
    store {
      id
      name
      email
      phone
    }
  }
}
