query coupons(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  coupons(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      isMultiple
      code
      name
      used
      info
      description
      codes {
        uniqueCode
        used
      }
      discount {
        type
        isPercent
        value
        currency
        excludeCategories
        shippingMethod
        product
        minProductQty
        maxProductQty
        category
        minProductPrice
        minOrderTotal
      }
      msg
      text
      terms
      color
      maxAmount
      maxUselimit
      oneUsePerCustomer
      oneUsePerUniqueCode
      validFrom
      validTo
      active
      createdAt
      updatedAt
    }
  }
}
