mutation saveColor(
  $id: String!
  $name: String
  $color_code: String
  $info: String
  $featured: Boolean
  $active: Boolean
) {
  saveColor(
    id: $id
    name: $name
    color_code: $color_code
    info: $info
    featured: $featured
    active: $active
  ) {
    id
    name
    color_code
    info
    featured
    active
    createdAt
    updatedAt
  }
}
