mutation saveColor(
  $id: String
  $name: String!
  $slug: String
  $active: Boolean
) {
  saveColor(id: $id, name: $name, slug: $slug, active: $active) {
    id
    name
    slug
    active
    createdAt
    updatedAt
  }
}
