mutation updateWithdrawal($id: ID!, $status: String, $remark: String) {
  updateWithdrawal(id: $id, status: $status, remark: $remark) {
    id
    status
    amount
    remark
    wallet
    user
    createdAt
    updatedAt
  }
}
