query withdrawal($id: ID!) {
  withdrawal(id: $id) {
    id
    status
    amount
    remark
    wallet {
      id
    }
    user {
      id
      email
      phone
    }
    createdAt
    updatedAt
  }
}
