query pageSlug($slug: String, $store: ID) {
  pageSlug(slug: $slug, store: $store) {
    id
    name
    slug
    title
    metaDescription
    keywords
    content
    menuTitle
    active
    createdAt
    updatedAt
  }
}
