query countries($page: Int, $search: String, $limit: Int, $sort: String) {
  countries(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      slug
      value
      code
      img
      flag
      lang
      states {
        name
      }
      sort
      active
      createdAt
      updatedAt
    }
  }
}
