mutation saveCountry(
  $id: String
  $name: String!
  $slug: String
  $value: String
  $code: String
  $img: String
  $flag: String
  $lang: String
  $sort: Int
  $active: Boolean
) {
  saveCountry(
    id: $id
    name: $name
    slug: $slug
    value: $value
    code: $code
    img: $img
    flag: $flag
    lang: $lang
    sort: $sort
    active: $active
  ) {
    id
    name
    slug
    value
    code
    img
    flag
    lang
    states {
      name
    }
    sort
    active
    createdAt
    updatedAt
  }
}
