mutation googleOneTap($credential: String!, $store: ID) {
  googleOneTap(credential: $credential, store: $store) {
    id
    email
    firstName
    lastName
    city
    phone
    avatar
    avatarCdn
    role
    verified
    active
    provider
    createdAt
    updatedAt
  }
}
