mutation googleOneTap($credential: String!) {
  googleOneTap(credential: $credential) {
    id
    email
    firstName
    lastName
    city
    phone
    avatar
    avatarCdn
    role
    verified
    active
    provider
    createdAt
    updatedAt
  }
}
