query me {
  me {
    id
    firstName
    lastName
    email
    phone
    gender
    role
    verified
    active
    provider
    active
    avatar
    avatarCdn
    referralCode
    currentBalance
    store
  }
}
