mutation register(
  $email: String!
  $password: String!
  $passwordConfirmation: String!
  $firstName: String
  $lastName: String
  $referralCode: String
  $role: String
  $phone: String
  $store: ID
) {
  register(
    email: $email
    password: $password
    passwordConfirmation: $passwordConfirmation
    firstName: $firstName
    lastName: $lastName
    referralCode: $referralCode
    role: $role
    phone: $phone
    store: $store
  ) {
    id
    email
    firstName
    lastName
    city
    phone
    role
    verified
    active
    avatar
    avatarCdn
    provider
    createdAt
    updatedAt
  }
}

# {
#   "email": "rojikaj967@viemery.com",
#   "password": "vacimod673",
#   "passwordConfirmation": "vacimod673",
#   "firstName": "vacimod",
#   "lastName": "673",
#   "referralCode": "rvvfe",
#   "role": "admin"
# }
