mutation saveUser(
  $id: String!
  $firstName: String
  $lastName: String
  $avatar: String
  $role: String
  $active: Boolean
  $verified: Boolean
  $gender: String
  $phone: String
  $email: String
  $shippingCharges: Int
  $freeShippingOn: Int
  $roles: [ID]
  $storeName: String
  $banner: String
) {
  saveUser(
    id: $id
    firstName: $firstName
    lastName: $lastName
    avatar: $avatar
    role: $role
    active: $active
    verified: $verified
    gender: $gender
    phone: $phone
    email: $email
    shippingCharges: $shippingCharges
    freeShippingOn: $freeShippingOn
    roles: $roles
    storeName: $storeName
    banner: $banner
  ) {
    id
    email
    firstName
    lastName
    role
    slug
    avatar
    avatarCdn
    gender
    phone
    active
    verified
    shippingCharges
    freeShippingOn
    storeName
    banner
    roles
  }
}

# {
#    "id": "626f967d2fa18405a0c05b2d",
#     "email": "xecesa6896@svcache.com",
#     "firstName": "xecesa6896",
#     "lastName": "xecesa6896",
#     "active": false,
#     "verified": false
# }
