mutation updateProfile(
  # $address: AddressInput
  $firstName: String
  $lastName: String
  $email: String
  $gender: String
  $phone: String # $avatar: String # $exam: String # $dob: String # # $state: String # $city: String
) # $phone: String
# $qualification: String # $experience: String # $subject: String
# $lang: String
# $facebook_url: String
# $twitter_url: String
# $info: InputInfo
{
  updateProfile(
    firstName: $firstName
    lastName: $lastName
    email: $email
    phone: $phone
    gender: $gender # avatar: $avatar #  # dob: $dob # info: $info # address: $address # qualification: $qualification # experience: $experience
  ) # subject: $subject
  # exam: $exam
  # lang: $lang
  # facebook_url: $facebook_url
  # twitter_url: $twitter_url
  {
    firstName
    lastName
    email
    # avatar
    # role
    # verified
    gender
    # city
    # qualification
    # experience
    # subject
    # exam
    # lang
    # facebook_url
    # twitter_url
    address {
      address
      town
      city
      state
      zip
    }
    info {
      public
      store
    }
  }
}
