mutation {
  updateProfile(
    firstName: "prakash"
    lastName: "jayaswal"
    email: "prakash@gmail.com"
    role: "admin"
    gender: "male"
    phone: "9694039047"
    dob: "191095"
    avatar: "String"
    provider: "String"
    active: true
    verified: true
    meta: "metaString"
    metaTitle: "Stringmetatitle"
    metaDescription: "metaDescString"
    metaKeywords: "metaKeyString"
  ) {
    firstName
    lastName
    phone
    email
    role
    gender
    avatar
    provider
    active
    verified
    address
    ratings
    reviews
    city
    meta
    metaTitle
    metaDescription
    metaKeywords
    createdAt
    updatedAt
  }
}
