query user($id: String!) {
  user(id: $id) {
    id
    email
    firstName
    lastName
    avatar
    avatarCdn
    city
    phone
    role
    verified
    active
    plan
    store
    createdAt
    updatedAt
  }
}
